name: Deploy Terraform to AWS
on:
  push:
    branches:
      - phong18data
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION_DEV }}

      - name: Unit testing
        run: |
          python -m pip install --upgrade pip
          pip install -r test/test-requirements.txt
          coverage run -m pytest test/test_extractor.py
          coverage report -m --fail-under=10

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
      
      - name: Setup terraform backend
        env:
          TF_VAR_your_account: ${{ secrets.Phong18 }}
        run: |
          cd terraform_backend
          terraform init
          terraform plan
          terraform apply --auto-approve
          cd ../
        continue-on-error: true

      - name: Terraform
        env:
          TF_VAR_your_account: ${{ secrets.Phong18 }}
        run: |
          cd terraform
          terraform init -backend-config="bucket=qa-community-${{ secrets.Phong18 }}-backend-s3"
          terraform plan
          terraform apply --auto-approve
          cd ../